from __future__ import annotations

STOPWORDS = {
    "vs",
    "v",
    "at",
    "@",
    "fc",
    "cf",
    "sc",
    "club",
    "the",
}

NBA_TEAM_ALIASES: dict[str, str] = {
    "atlanta hawks": "atlanta hawks",
    "boston celtics": "boston celtics",
    "brooklyn nets": "brooklyn nets",
    "charlotte hornets": "charlotte hornets",
    "chicago bulls": "chicago bulls",
    "cleveland cavaliers": "cleveland cavaliers",
    "dallas mavericks": "dallas mavericks",
    "denver nuggets": "denver nuggets",
    "detroit pistons": "detroit pistons",
    "golden state warriors": "golden state warriors",
    "houston rockets": "houston rockets",
    "indiana pacers": "indiana pacers",
    "los angeles clippers": "los angeles clippers",
    "la clippers": "los angeles clippers",
    "los angeles lakers": "los angeles lakers",
    "la lakers": "los angeles lakers",
    "memphis grizzlies": "memphis grizzlies",
    "miami heat": "miami heat",
    "milwaukee bucks": "milwaukee bucks",
    "minnesota timberwolves": "minnesota timberwolves",
    "new orleans pelicans": "new orleans pelicans",
    "new york knicks": "new york knicks",
    "oklahoma city thunder": "oklahoma city thunder",
    "orlando magic": "orlando magic",
    "philadelphia 76ers": "philadelphia 76ers",
    "philly": "philadelphia 76ers",
    "phoenix suns": "phoenix suns",
    "portland trail blazers": "portland trail blazers",
    "sacramento kings": "sacramento kings",
    "san antonio spurs": "san antonio spurs",
    "spurs": "san antonio spurs",
    "toronto raptors": "toronto raptors",
    "utah jazz": "utah jazz",
    "washington wizards": "washington wizards",
}

SOCCER_TEAM_ALIASES: dict[str, str] = {
    "arsenal": "arsenal",
    "aston villa": "aston villa",
    "bournemouth": "afc bournemouth",
    "afc bournemouth": "afc bournemouth",
    "brentford": "brentford",
    "brighton": "brighton & hove albion",
    "brighton and hove albion": "brighton & hove albion",
    "burnley": "burnley",
    "chelsea": "chelsea",
    "crystal palace": "crystal palace",
    "everton": "everton",
    "fulham": "fulham",
    "ipswich": "ipswich town",
    "ipswich town": "ipswich town",
    "leicester": "leicester city",
    "leicester city": "leicester city",
    "liverpool": "liverpool",
    "man city": "manchester city",
    "manchester city": "manchester city",
    "man united": "manchester united",
    "man utd": "manchester united",
    "manchester united": "manchester united",
    "newcastle": "newcastle united",
    "newcastle united": "newcastle united",
    "nottingham forest": "nottingham forest",
    "southampton": "southampton",
    "tottenham": "tottenham hotspur",
    "tottenham hotspur": "tottenham hotspur",
    "spurs": "tottenham hotspur",
    "west ham": "west ham united",
    "west ham united": "west ham united",
    "wolves": "wolverhampton wanderers",
    "wolverhampton": "wolverhampton wanderers",
    "wolverhampton wanderers": "wolverhampton wanderers",
    "real madrid": "real madrid",
    "barcelona": "barcelona",
    "atletico madrid": "atletico madrid",
    "sevilla": "sevilla",
    "juventus": "juventus",
    "galatasaray": "galatasaray",
}


def aliases_for_sport(sport: str) -> dict[str, str]:
    if sport == "NBA":
        return NBA_TEAM_ALIASES
    if sport == "SOCCER":
        return SOCCER_TEAM_ALIASES
    return {}
