from __future__ import annotations

STOPWORDS = {
    "vs",
    "v",
    "at",
    "@",
    "fc",
    "cf",
    "sc",
    "club",
    "the",
}

NBA_TEAM_ALIASES: dict[str, str] = {
    "atlanta hawks": "atlanta hawks",
    "atlanta": "atlanta hawks",
    "atl": "atlanta hawks",
    "boston celtics": "boston celtics",
    "boston": "boston celtics",
    "bos": "boston celtics",
    "brooklyn nets": "brooklyn nets",
    "brooklyn": "brooklyn nets",
    "bkn": "brooklyn nets",
    "charlotte hornets": "charlotte hornets",
    "charlotte": "charlotte hornets",
    "cha": "charlotte hornets",
    "chicago bulls": "chicago bulls",
    "chicago": "chicago bulls",
    "chi": "chicago bulls",
    "cleveland cavaliers": "cleveland cavaliers",
    "cleveland": "cleveland cavaliers",
    "cavs": "cleveland cavaliers",
    "cle": "cleveland cavaliers",
    "dallas mavericks": "dallas mavericks",
    "dallas": "dallas mavericks",
    "mavs": "dallas mavericks",
    "dal": "dallas mavericks",
    "denver nuggets": "denver nuggets",
    "denver": "denver nuggets",
    "den": "denver nuggets",
    "detroit pistons": "detroit pistons",
    "detroit": "detroit pistons",
    "det": "detroit pistons",
    "golden state warriors": "golden state warriors",
    "golden state": "golden state warriors",
    "warriors": "golden state warriors",
    "gsw": "golden state warriors",
    "houston rockets": "houston rockets",
    "houston": "houston rockets",
    "hou": "houston rockets",
    "indiana pacers": "indiana pacers",
    "indiana": "indiana pacers",
    "ind": "indiana pacers",
    "los angeles clippers": "los angeles clippers",
    "la clippers": "los angeles clippers",
    "los angeles c": "los angeles clippers",
    "clippers": "los angeles clippers",
    "lac": "los angeles clippers",
    "los angeles lakers": "los angeles lakers",
    "la lakers": "los angeles lakers",
    "los angeles l": "los angeles lakers",
    "lakers": "los angeles lakers",
    "lal": "los angeles lakers",
    "memphis grizzlies": "memphis grizzlies",
    "memphis": "memphis grizzlies",
    "grizzlies": "memphis grizzlies",
    "mem": "memphis grizzlies",
    "miami heat": "miami heat",
    "miami": "miami heat",
    "mia": "miami heat",
    "milwaukee bucks": "milwaukee bucks",
    "milwaukee": "milwaukee bucks",
    "mil": "milwaukee bucks",
    "minnesota timberwolves": "minnesota timberwolves",
    "minnesota": "minnesota timberwolves",
    "timberwolves": "minnesota timberwolves",
    "min": "minnesota timberwolves",
    "new orleans pelicans": "new orleans pelicans",
    "new orleans": "new orleans pelicans",
    "pelicans": "new orleans pelicans",
    "nop": "new orleans pelicans",
    "new york knicks": "new york knicks",
    "new york": "new york knicks",
    "knicks": "new york knicks",
    "nyk": "new york knicks",
    "oklahoma city thunder": "oklahoma city thunder",
    "oklahoma city": "oklahoma city thunder",
    "thunder": "oklahoma city thunder",
    "okc": "oklahoma city thunder",
    "orlando magic": "orlando magic",
    "orlando": "orlando magic",
    "magic": "orlando magic",
    "orl": "orlando magic",
    "philadelphia 76ers": "philadelphia 76ers",
    "philadelphia": "philadelphia 76ers",
    "philly": "philadelphia 76ers",
    "76ers": "philadelphia 76ers",
    "phi": "philadelphia 76ers",
    "phoenix suns": "phoenix suns",
    "phoenix": "phoenix suns",
    "suns": "phoenix suns",
    "phx": "phoenix suns",
    "portland trail blazers": "portland trail blazers",
    "portland": "portland trail blazers",
    "trail blazers": "portland trail blazers",
    "blazers": "portland trail blazers",
    "por": "portland trail blazers",
    "sacramento kings": "sacramento kings",
    "sacramento": "sacramento kings",
    "kings": "sacramento kings",
    "sac": "sacramento kings",
    "san antonio spurs": "san antonio spurs",
    "san antonio": "san antonio spurs",
    "spurs": "san antonio spurs",
    "sas": "san antonio spurs",
    "toronto raptors": "toronto raptors",
    "toronto": "toronto raptors",
    "raptors": "toronto raptors",
    "tor": "toronto raptors",
    "utah jazz": "utah jazz",
    "utah": "utah jazz",
    "jazz": "utah jazz",
    "uta": "utah jazz",
    "washington wizards": "washington wizards",
    "washington": "washington wizards",
    "wizards": "washington wizards",
    "was": "washington wizards",
}

SOCCER_TEAM_ALIASES: dict[str, str] = {
    "arsenal": "arsenal",
    "aston villa": "aston villa",
    "bournemouth": "afc bournemouth",
    "afc bournemouth": "afc bournemouth",
    "brentford": "brentford",
    "brighton": "brighton & hove albion",
    "brighton and hove albion": "brighton & hove albion",
    "burnley": "burnley",
    "chelsea": "chelsea",
    "crystal palace": "crystal palace",
    "everton": "everton",
    "fulham": "fulham",
    "ipswich": "ipswich town",
    "ipswich town": "ipswich town",
    "leicester": "leicester city",
    "leicester city": "leicester city",
    "liverpool": "liverpool",
    "man city": "manchester city",
    "manchester city": "manchester city",
    "man united": "manchester united",
    "man utd": "manchester united",
    "manchester united": "manchester united",
    "newcastle": "newcastle united",
    "newcastle united": "newcastle united",
    "nottingham forest": "nottingham forest",
    "southampton": "southampton",
    "tottenham": "tottenham hotspur",
    "tottenham hotspur": "tottenham hotspur",
    "spurs": "tottenham hotspur",
    "west ham": "west ham united",
    "west ham united": "west ham united",
    "wolves": "wolverhampton wanderers",
    "wolverhampton": "wolverhampton wanderers",
    "wolverhampton wanderers": "wolverhampton wanderers",
    "real madrid": "real madrid",
    "barcelona": "barcelona",
    "atletico madrid": "atletico madrid",
    "sevilla": "sevilla",
    "juventus": "juventus",
    "galatasaray": "galatasaray",
}


def aliases_for_sport(sport: str) -> dict[str, str]:
    if sport == "NBA":
        return NBA_TEAM_ALIASES
    if sport == "SOCCER":
        return SOCCER_TEAM_ALIASES
    return {}
